---
title: "Build Home Model"
author: "Alan Jackson"
format: html
editor: visual
---

## Build a Home model

Home will be a function of Temperature, vacation, and time of day

```{r initialize}

library(tidyverse)
library(lubridate)
library(scales)

path <- "/home/ajackson/Dropbox/Rprojects/Tulane_Solar/Data/"

tz <- "America/Chicago"

df <- readRDS(paste0(path, "Smart.rds"))
Vaca <- readRDS(paste0(path, "Vacation.rds"))
Weather <- readRDS(paste0(path, "Weather.rds")) %>% 
  filter(Date>lubridate::mdy_hms("01-01-2021T00:00:00")) %>% 
  filter(!is.na(Temperature))
Solar_old <- readRDS(paste0(path, "Solar_old.rds"))

Solar_old <- Solar_old %>% #    Clean up old data and calc Max values by time
  filter(Solar_W<6000) %>% 
  mutate(DST=dst(Timestamp)) %>% 
  mutate(Date=date(Timestamp)) %>%
  mutate(Hour=hour(Timestamp) + minute(Timestamp)/15*0.25,  
         Month=month(Timestamp), Day=day(Timestamp)) %>%
  mutate(Hour=if_else(DST, Hour-1, Hour)) 

df <- df %>% filter(!is.na(Usage)) %>% 
  mutate(Vacation=if_else(lubridate::as_date(Date) %in% Vaca, TRUE, FALSE))

```

##        Clean up Weather data

All I need is temperature every 15 minutes

```{r weather}
tz <- "America/Chicago"

xout <- seq(mdy_hm("01-01-2021T00:00", tz=tz),
            mdy_hm("12-31-2022T00:00", tz=tz),
            by=15*60)

Weather_T <- approx(Weather$Date, Weather$Temperature, xout=xout)

Weather_trp <- as_tibble(bind_cols(Date=Weather_T$x, 
                    Temperature=Weather_T$y))

```












